//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Linq;
namespace Разработка_информационной_системы_по_учету_ремонта
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Technic
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Amount { get; set; }
        public Nullable<int> KomuVidan { get; set; }
        public string KomuVidanStr
        {
            get
            {
                Clients Clients = App.Database1Entities.Clients.Single(x=>x.Id == KomuVidan);
                return Clients.Surname + " " + Clients.Name + " " + Clients.FutherName;
            }
        }
    }
}
